version: '3'
services:
  # from docker hub
  postgres:
    image: 'postgres:latest'
  # from docker hub
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build: 
      # name of file
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3050:80'
  # created in ./server directory
  api:
    depends_on:
      - postgres
    build: 
      # name of file
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    # set environmental variables here
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  # created in ./client directory
  client:
    build: 
      # name of file
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
  # created in ./worker directory
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build: 
      # name of file
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app